Amaiate seller service follower list
mtocura/desafio_spring pull request #32
Opened 2021-07-07 20:47 UTC by amaiate

2021-07-07 21:00 UTC, angelo-salles requested changes
na linha 52 do SellerService trocar a mensagem estática pela mensagem do erro capturado

2021-07-07 21:06 UTC, joaonunesmeli requested changes

2021-07-07 21:06 UTC, joaonunesmeli commented on src/main/java/br/com/bootcamp/desafio_spring/service/SellerService.java
> +            if (user.getIsSeller()) {
É bom evitar estruturas aninhadas. Neste "if" caso se testasse a condição contrária* o código ficaria mais "vertical" e menos "horizontal". Condição: "if(!user.getIsSeller())".

2021-07-07 21:15 UTC, amaiate commented on src/main/java/br/com/bootcamp/desafio_spring/service/SellerService.java
> +            if (user.getIsSeller()) {
Alterações efetuadas, obrigada pela dica ;)

2021-07-08 11:16 UTC, mtocura requested changes

2021-07-08 11:16 UTC, mtocura commented on src/main/java/br/com/bootcamp/desafio_spring/controller/SellerController.java
> +    public ResponseEntity<?> getFollowedList(@PathVariable int userId) {
Adiciona mais um parâmetro no método para receber a query param de ordenação
`public ResponseEntity<?> getFollowedList(@PathVariable int userId, @RequestParam(required = false) String order)`

Ai ajusta o sellerService.followerList para receber o order também como parâmetro, ficando da seguinte maneira a chamada do método:
`return ResponseEntity.ok(sellerService.followerList(userId, order == null ? "" : order));`

2021-07-08 11:16 UTC, mtocura commented on src/main/java/br/com/bootcamp/desafio_spring/service/SellerService.java
> +    public SellerFollowersListDTO followerList (int userId) {
Ajusta aqui para receber a String order como parâmetro também. E depois que você obter o `followersUser` você ordena de acordo com o parâmetro de ordenação passado, caso ele corresponda a algum tipo de ordenação

```
if(order.equals("name_asc")) {
       SortByName.sortByNameASC(followersUser);
}

if(order.equals("name_desc")) {
    SortByName.sortByNameDESC(followersUser);
}
```

2021-07-08 12:20 UTC, amaiate commented on src/main/java/br/com/bootcamp/desafio_spring/controller/SellerController.java
> +    public ResponseEntity<?> getFollowedList(@PathVariable int userId) {
Boa, alterações efetuadas ;)

2021-07-08 12:20 UTC, amaiate commented on src/main/java/br/com/bootcamp/desafio_spring/service/SellerService.java
> +    public SellerFollowersListDTO followerList (int userId) {
Boa, alterações efetuadas ;)

2021-07-08 12:21 UTC, mtocura approved these changes

2021-07-08 12:39 UTC, joaonunesmeli approved these changes

2021-07-08 12:40 UTC, merged